main: fr.pederobien.minecraft.hungergame.HGPlugin
name: minecraft-hungergame
version: 1.0_MC_1.13.2-SNAPSHOT
api-version: 1.13
depend: [minecraft-border, minecraft-rules]
softdepend: [minecraft-chat]

description:
commands:
  hg:
    description: This command is used to configure an hunger game.
    permission: HGPlugin.permission